-- AlterTable
ALTER TABLE "DetailedActivity" ADD COLUMN     "available_zones" JSONB,
ADD COLUMN     "average_heartrate" DOUBLE PRECISION,
ADD COLUMN     "display_hide_heartrate_option" BOOLEAN,
ADD COLUMN     "from_accepted_tag" BOOLEAN,
ADD COLUMN     "has_heartrate" BOOLEAN,
ADD COLUMN     "heartrate_opt_out" BOOLEAN,
ADD COLUMN     "location_city" TEXT,
ADD COLUMN     "location_country" TEXT,
ADD COLUMN     "location_state" TEXT,
ADD COLUMN     "max_heartrate" DOUBLE PRECISION,
ADD COLUMN     "perceived_exertion" INTEGER,
ADD COLUMN     "pr_count" INTEGER,
ADD COLUMN     "prefer_perceived_exertion" BOOLEAN,
ADD COLUMN     "resource_state" INTEGER,
ADD COLUMN     "similar_activities" JSONB,
ADD COLUMN     "stats_visibility" JSONB,
ADD COLUMN     "suffer_score" INTEGER,
ADD COLUMN     "utc_offset" INTEGER,
ADD COLUMN     "visibility" TEXT;
