-- CreateTable
CREATE TABLE "DetailedActivity" (
    "id" TEXT NOT NULL,
    "external_id" TEXT,
    "upload_id" TEXT,
    "athlete" JSONB NOT NULL,
    "name" TEXT NOT NULL,
    "distance" DOUBLE PRECISION NOT NULL,
    "moving_time" INTEGER NOT NULL,
    "elapsed_time" INTEGER NOT NULL,
    "total_elevation_gain" DOUBLE PRECISION NOT NULL,
    "elev_high" DOUBLE PRECISION,
    "elev_low" DOUBLE PRECISION,
    "type" TEXT NOT NULL,
    "sport_type" TEXT NOT NULL,
    "start_date" TIMESTAMP(3) NOT NULL,
    "start_date_local" TIMESTAMP(3) NOT NULL,
    "timezone" TEXT NOT NULL,
    "start_latlng" JSONB,
    "end_latlng" JSONB,
    "achievement_count" INTEGER NOT NULL,
    "kudos_count" INTEGER NOT NULL,
    "comment_count" INTEGER NOT NULL,
    "athlete_count" INTEGER NOT NULL,
    "photo_count" INTEGER NOT NULL,
    "total_photo_count" INTEGER NOT NULL,
    "map" JSONB NOT NULL,
    "trainer" BOOLEAN NOT NULL,
    "commute" BOOLEAN NOT NULL,
    "manual" BOOLEAN NOT NULL,
    "private" BOOLEAN NOT NULL,
    "flagged" BOOLEAN NOT NULL,
    "workout_type" INTEGER,
    "upload_id_str" TEXT,
    "average_speed" DOUBLE PRECISION NOT NULL,
    "max_speed" DOUBLE PRECISION NOT NULL,
    "has_kudoed" BOOLEAN NOT NULL,
    "hide_from_home" BOOLEAN,
    "gear_id" TEXT,
    "kilojoules" DOUBLE PRECISION,
    "average_watts" DOUBLE PRECISION,
    "device_watts" BOOLEAN,
    "max_watts" INTEGER,
    "weighted_average_watts" INTEGER,
    "description" TEXT,
    "photos" JSONB,
    "gear" JSONB,
    "calories" DOUBLE PRECISION,
    "segment_efforts" JSONB,
    "device_name" TEXT,
    "embed_token" TEXT,
    "splits_metric" JSONB,
    "splits_standard" JSONB,
    "laps" JSONB,
    "best_efforts" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DetailedActivity_pkey" PRIMARY KEY ("id")
);
